apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    name: pv001
spec:
  nfs:
    path: /data/nfs/v1
    server: 192.168.10.75
  accessModes: [ "ReadWriteOnce","ReadWriteMany" ]
  capacity:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
    name: pv002
spec:
  nfs:
    path: /data/nfs/v2
    server: 192.168.10.75
  accessModes: [ "ReadWriteOnce","ReadWriteMany" ]
  capacity:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
  labels:
    name: pv003
spec:
  nfs:
    path: /data/nfs/v3
    server: 192.168.10.75
  accessModes: [ "ReadWriteOnce","ReadWriteMany" ]
  capacity:
    storage: 5Gi
