version: "3"
services:
  jenkins:
    image: xiangys0134/jenkins:centos-v1.0.1
    container_name: jenkins
    restart: always
    privileged: true
    ports:
      - 8180:8080
      - 50000:50000
    volumes:
      - ./jenkins_data:/data/jenkins
      - ./jenkins_backup:/data/jenkins_backup
    networks:
      - ssg-jenkins

  agent-maven-web:
    #image: xiangys0134/agent:agent-maven-v1.0.1
    image: test:v0.2
    container_name: agent-maven-web
    restart: always
    privileged: true
    command: ["sleep 3600"]
    environment:
      - JENKINS_URL=http://jenkins:8080/computer/web-build/slave-agent.jnlp
      - JENKINS_SECRET=bf8737fed9f9fc5708a2b50f70e144a00b98207cfff092bf057aa040384890fd
      - JENKINS_AGENT_WORKDIR=/data/jenkins
    volumes:
      - ./agent-maven-web/conf/settings.xml:/usr/local/apache-maven-3.6.1/conf/settings.xml
    networks:
      - ssg-jenkins

networks:
  ssg-jenkins: 
