apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - name: http
          containerPort: 9090
     #   volumeMounts:
     #   - name: config
     #     mountPath: /etc/prometheus/prometheus.yml
      #nodeSelector:
      #  slave: k8s-node01
    #volumes:
    #- name: config
    #  hostPath:
    #    path: /tmp/prometheus.yml

---

apiVersion: v1
kind: Service
metadata:
  name: svc-prometheus
  namespace: default
spec:
  selector:
    app: prometheus
  #clusterIP: k8s-node01
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
