version: "3"
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    restart: always
    volumes:
      - ./etc/config/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/config/proxy_java.conf:/etc/nginx/proxy_java.conf
      - ./etc/config/conf.d:/etc/nginx/conf.d
      - ./etc/letsencrypt/:/etc/letsencrypt/
      - ./html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_ent

networks:
  nginx_ent:
