version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    #deploy:
    #  replicas: 1
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
