spring:
  application:
    name: xone-register-server
  main:
    banner-mode: 'OFF'
eureka:
  instance:
    hostname: xone-registration
    lease-expiration-duration-in-seconds: 60 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间
  client:
    fetch-registry: false    #是否检索服务
    register-with-eureka: false    #是否向服务注册中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 5000 #服务清理间隔单位毫秒
    enable-self-preservation: false #关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
    responseCacheUpdateIntervalMs: 3000 #刷新readCacheMap的时间

server:
  port: 9761

#actuator监控点
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback-spring.xml
