eureka:
  client:
    serviceUrl:
      defaultZone: http://zhaozheng-public-osp-registry-service:8761/eureka/
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
  instance:
    # 心跳间隔
    lease-renewal-interval-in-seconds: 10
    # 若5s内没有发，则会被踢
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
server:
  port: 8762

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  eager-load:
    enabled: true
    clients: USER-SERVICE,OAUTH-SERVICE,BOND-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.179:3306/xcbsmp_common?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql.admin.pass
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
        multi-statement-allow: true
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        #serviceId: eureka-service
      fail-fast: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_route
          uri: lb://USER-SERVICE
          order: 3
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: quartz_route
          uri: lb://QUARTZ-SERVICE
          order: 2
          predicates:
            - Path=/system/quartz/**
          filters:
            - StripPrefix=2
        - id: oauth_route
          uri: lb://OAUTH-SERVICE
          order: 1
          predicates:
            - Path=/system/oauth/**
          filters:
            - StripPrefix=2

logging:
  config: classpath:config/logback-spring.xml


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xctech.gateway.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#扩展系统标志和排除的uri
#gwext:
#  sysmap: {'test1': 'test1'}
#  excludeuri:
#    - /test
#    - /test1

