version: "3"
services:
  jenkins:
    image: xiangys0134/jenkins:master-v1.0.1
    container_name: jenkins
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_data:/data/jenkin
      - ./jenkins_backup:/data/jenkins_backup
    networks:
      - xunce
networks:
  xunce: 
