version: '3'
services:
  xiangys0134-mysql:
    image: mysql:5.7.27
    container_name: xiangys0134-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Aa123456'
      MYSQL_DATABASE: 'tech'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '123456'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    ports:
      - 13306:3306
    networks:
      - xunce

networks:
  xunce:
