server:
  port: 9781

eureka:
  client:
    serviceUrl:
      defaultZone: http://xone-registration:9761/eureka/
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
  instance:
    # 心跳间隔
    lease-renewal-interval-in-seconds: 10
    # 若5s内没有发，则会被踢
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}

spring:
  application:
    name: attachment
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.0.178:22122

security:
  authorize:
    ignored-uri:
      - /v2/api-docs
      - /swagger-resources/**
      - /swagger-ui.html**
      - /webjars/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
