version: "3"
services:
  fastdfs:
    image: fastdfs:v0.4
    container_name: fastdfs
    restart: always
    privileged: true
    volumes:
      - ./etc/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./etc/proxy_java.conf:/usr/local/nginx/conf/proxy_java.conf
      - ./etc/conf.d:/usr/local/nginx/conf/conf.d
      - ./data:/data
    ports:
      - "22122:22122"
      - "23000:23000"
      - "8080:80"
    networks:
      - fastdfs_verlay

networks:
  fastdfs_verlay:
