version: "3"
services:
#--------------------------------------java后端----------------------------------------#
  xone-registration:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-registration
    container_name: xone-registration
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64
    command: ['/data/XONE/xone-registration/bin/docker-entrypoint.sh','start']
    ports:
      - 9761:9761
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-configuration:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-configuration
    container_name: xone-configuration
    command: ['/data/XONE/xone-configuration/bin/docker-entrypoint.sh','start']
    ports:
      - 9763:9763
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-authorization:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-authorization
    container_name: xone-authorization
    command: ['/data/XONE/xone-authorization/bin/docker-entrypoint.sh','start']
    ports:
      - 9766:9766
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-foundation:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-foundation
    container_name: xone-foundation
    command: ['/data/XONE/xone-foundation/bin/docker-entrypoint.sh','start']
    ports:
      - 9767:9767
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-instruction:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-instruction
    container_name: xone-instruction
    command: ['/data/XONE/xone-instruction/bin/docker-entrypoint.sh','start']
    ports:
      - 9768:9768
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-workflow:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-workflow
    container_name: xone-workflow
    command: ['/data/XONE/xone-workflow/bin/docker-entrypoint.sh','start']
    ports:
      - 9769:9769
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-attachment:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-attachment
    container_name: xone-attachment
    command: ['/data/XONE/xone-attachment/bin/docker-entrypoint.sh','start']
    ports:
      - 9781:9781
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-gateway:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-java:v2.2.0
    #restart: always
    hostname: xone-gateway
    container_name: xone-gateway
    command: ['/data/XONE/xone-gateway/bin/docker-entrypoint.sh','start']
    ports:
      - 9762:9762
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

#--------------------------------------fastdfs----------------------------------------#
  xone-fastdfs:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/xone-fastdfs:v1.0.5
    #restart: always
    hostname: xone-fastdfs
    container_name: xone-fastdfs
    volumes:
      - ./config/nginx/fdfs.conf:/etc/nginx/conf.d/fdfs.conf
      - ./fdfs/conf/storage.conf:/etc/fdfs/storage.conf
      - ./fdfs/data:/data/fastdfs/storage/data
    ports:
      - 22122:22122
      - 23000:23000
    privileged: true
    networks:
      - xunce

#--------------------------------------数据库----------------------------------------#
  xc-xone-mysql:
    image: mysql:8.0.18
    restart: always
    container_name: xc-xone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql.admin.pass'
      MYSQL_DATABASE: 'tech'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'AH*1234dfasA56'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    ports:
      - 23306:3306
    networks:
      - xunce
networks:
  xunce:
