apiVersion: v1
kind: Pod
metadata: 
  name: pod-cm-1
  namespace: default
  labels: 
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: nginx
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 80
    env:
    - name: NGINX_SERVER_PORT
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: nginx_port
    - name: NGINX_SERVER_NAME
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: server_name
    - name: NGINX_SERVER_APP
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: app
    - name: NGINX_SERVER_PR
      valueFrom:
        configMapKeyRef:
          name: game-config
          key: game.properties
