version: "3"
services:
  xunce-xone-back:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/zhaoshangxone:XONE-v2.1.0
    restart: always
    hostname: xunce-xone-back
    container_name: xunce-xone-back
    volumes:
      - ./config/xone-configuration/config/authorization/dev/application.yml:/data/XONE/xone-configuration/config/authorization/dev/application.yml
      - ./config/xone-configuration/config/foundation/dev/application.yml:/data/XONE/xone-configuration/config/foundation/dev/application.yml
      - ./config/xone-configuration/config/gateway/dev/application.yml:/data/XONE/xone-configuration/config/gateway/dev/application.yml
      - ./config/xone-configuration/config/instruction/dev/application.yml:/data/XONE/xone-configuration/config/instruction/dev/application.yml
      - ./config/xone-configuration/config/messaging/dev/application.yml:/data/XONE/xone-configuration/config/messaging/dev/application.yml
      - ./config/xone-configuration/config/workflow/dev/application.yml:/data/XONE/xone-configuration/config/workflow/dev/application.yml
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
  xunce-xone-front:
    image: registry.cn-hangzhou.aliyuncs.com/xunceprivate/zhaoshangxone:xc-front-xone-v2.1.0
    restart: always
    hostname: xunce-xone-front
    container_name: xunce-xone-front
    volumes:
      - ./config/nginx/xc-front-xone.conf:/etc/nginx/conf.d/xc-front-xone.conf
    ports:
      - 8060:8060
    privileged: true
    networks:
      - xunce
  xc-xone-mysql:
    image: mysql:8.0.18
    restart: always
    container_name: xc-xone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql.admin.pass'
      MYSQL_DATABASE: 'tech'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'AH*1234dfasA56'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    ports:
      - 23306:3306
    networks:
      - xunce
networks:
  xunce: