apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  hostname: busybox-1
  hostAliases:
  - ip: "192.168.0.223"
    hostnames:
    - "cdh0"
  - ip: "192.168.0.224"
    hostnames:
    - "cdh1"
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
