apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: default
spec:
  selector:
    name: app-nfs
    version: stable
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30002
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-nfs
  namespace: default
  labels: 
    name: app-nfs
    version: stable
spec:
  replicas: 8
  template:
    metadata:
      labels:
        name: app-nfs
        version: stable
    spec:
      containers:
      - name: web
        image: nginx:1.16.0
        ports: 
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nfs
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nfs
        nfs:
          path: /data/nfs
          server: 192.168.10.75
        
