apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
spec:
  hostname: busybox-1
  hostAliases:
  - ip: "192.168.0.223"
    hostnames:
    - "cdh0"
  - ip: "192.168.0.224"
    hostnames:
    - "cdh1"
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443
    volumeMounts: 
    - name: html
      mountPath: /usr/share/nginx/html/
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do echo $(date) >> /data/index.html; sleep 2; done"
    volumeMounts:
    - name: html
      mountPath: /data/
  volumes:
  - name: html
    emptyDir: {}
      
