apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-hostpath
  namespace: default
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html/
    ports:
    - name: http
      containerPort: 80
  volumes:
  - name: html
    nfs:
      path: /data/nfs
      server: 192.168.10.75
