apiVersion: v1
kind: Pod
metadata: 
  name: pod-demo
  namespace: default
  labels: 
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  nodeSelector:
    gpu: harddisk
  containers:
  - name: myapp
    image: nginx
