apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: myapp
      release: canary
  template:
    metadata: 
      name: nginx
      labels: 
        app: myapp
        release: canary
        environment: qa
        type: tier
    spec:
      containers:
      - name: myapp-container
        image: nginx:1.16.0
        ports:
        - name: http
          containerPort: 80
        
        
