spring:
  application:
    name: configuration
  main:
    banner-mode: 'OFF'
  profiles:
    active: native
  cloud:
    config:
      server:
        native:  #本地仓库
          search-locations: "classpath:/config/{application}/{profile}"

server:
  port: 9763


eureka:
  client:
    serviceUrl:
      defaultZone: http://xone-registration:9761/eureka/
  instance:
    # 心跳间隔
    lease-renewal-interval-in-seconds: 5
    # 若5s内没有发，则会被踢
    lease-expiration-duration-in-seconds: 31
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:config/logback-spring.xml
