apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
    release: canary
  clusterIP: 10.97.97.99
  type: NodePort
  ports: 
  - name: myapp
    port: 80
    targetPort: 80
    nodePort: 30001
