version: '3'
services:
  mysql:
    image: mysql:5.6.43
    container_name: mysql01
    environment:
      - MYSQL_DATABASE=tu
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    #mem_limit: 2g
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/mysql-conf:/etc/mysql/conf.d
      - ./mysql/mysql-logs:/var/log    
    networks:
      - esnet
    ports:
      - "23306:3306"
networks:
  esnet:
    driver: bridge 
