version: '3'
services:
  redis-6380:
    image: redis:5.0.5
    container_name: redis-6380
    ports:
      - 6380:6379
    command: ["redis-server","/etc/redis/redis.conf"]
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
    networks:
      - enst
networks:
  enst:

